#!/bin/zsh

MNT=/mnt/ftfs
MOD=ftfs

function do_unmount()
{
    mountpoint /mnt/ftfs >/dev/null &&
        sudo umount $MNT
}

function do_mount()
{
    sudo mount -t $1 /dev/loop0 $MNT
}


function usage()
{
    echo "usage $1 (help|init|u|ext2|ftfs|mod|sh)+"
}


for arg in $@; do
    case $arg in
        ("help"|"-h")
            usage $0
            ;;
        ("init")
            sudo losetup -f img
            ;;
        ("u")
            do_unmount
            ;;
        ("ext2")
            do_unmount
            do_mount ext2
            ;;
        ("ftfs")
            do_unmount
            do_mount fortytwofs
            ;;
        ("mod")
            lsmod | grep $MOD &&
                sudo rmmod $MOD
            make &&
                sudo insmod $MOD.ko
            ;;
        ("sh")
            pushd $MNT
            sudo bash
            popd
            ;;
        (*)
            echo unknown arg $arg
            usage $0
            ;;
    esac
done
